name: Clubhouse Workflow State
description: Move stories between workflow states
branding:
  icon: arrow-right-circle
  color: blue
inputs:
  chToken:
    description: Clubhouse API auth token
    required: true
  fromStateId:
    description: Move from state id
    required: true
  toStateId:
    description: Move to state id
    required: true
runs:
  using: "node12"
  main: "index.js"
